### ISSUE TITLE
[Improvement] - Build Module for Zane

### ISSUE THREAD

**Issue by thomasnguyen** [thomasnguyen/BLTrees#3]
- [x] Create a new component for zane skills
- [x] Fill in tree #1 
- [x] Fill in tree #2 
- [x] Fill in tree #3 

- [x] Download all of zane's skill icons
- [x] Create logic for zane's special skills
- [x] Create avatar for zane
